#!/bin/sh
datetime=$(date +"%Y%m%d%H%M%S")
dbname=mydatabase

mysqldump -uroot -R --databases --add-drop-database --default-character-set=utf8 -h 127.0.0.1 $dbname > /data/backup/$dbname-backup-$datetime.sql
echo /data/backup/$dbname-backup-$datetime.sql >> /data/backup/database-backup.list
