#!/bin/bash

user=backuper
backuplistdir=/data/backup
backuplistfile=$backuplistdir/database-backup.list
host=www.server.com
scp $user@$host:/data/backup/database-backup.list $backuplistfile

line=$(tail -1 $backuplistfile)
filename=$(basename $line)

scp $user@$host:$line $backuplistdir/database/$fe

echo "backup file saved to ": $backuplistdir/database/$filename
