#!/bin/bash

user=backuper
backuplistdir=/data/backup
backuplistfile=$backuplistdir/database-backup.list
host=www.server.com
scp $user@$host:/data/backup/database-backup.list $backuplistfile

tail -1 $backuplistfile | while read line
do
 echo $line
 basename $line | while read fe
 do
  scp $user@$host:$line $backuplistdir/$fe
 done
done
